version: '3.8'

services:
  orchestrator:
    build: ./orchestrator
    command: ./orchestrator
    volumes:
      - ./orchestrator/internal/database:/orchestrator/internal/database
    ports:
      - 8000:8000
    environment:
      - TZ=UTC

      - TIME_ADDITION_MS
      - TIME_SUBTRACTION_MS
      - TIME_MULTIPLICATIONS_MS
      - TIME_DIVISIONS_MS

      - HTTP_PORT

      - GRPC_HOST
      - GRPC_PORT
    networks:
      - app-network

  agent:
    build: ./agent
    command: ./agent
    ports:
      - 8080:8080
    depends_on:
      - orchestrator
    environment:
      - COMPUTING_POWER

      - GRPC_HOST
      - GRPC_PORT
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
