name: Agent_CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  agent-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agent
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23
    
    - name: Build
      run: go build ./...
    
    - name: Vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./...

    - name: Run tests
      run: go test -race -vet=off ./...