File: .github/workflows/agent_test.yaml
name: Agent_CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  agent-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23
    
    - name: Build
      run: |
        cd agent
        set -a && source ../.env.example && set +a
        set GRPC_HOST="localhost"
        go build ./...
    
    - name: Vet
      run: |
        go vet ./...
        cd agent

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: |
        staticcheck ./...
        cd agent

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: |
        golint ./...
        cd agent

    - name: Run tests
      run: go test -race -vet=off ./...