File: .github/workflows/integration_test.yaml
name: Integration_Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23
      
    - name: Orchestrator build
      run: |
        cd orchestrator
        set -a && source ../.env.example && set +a
        set GRPC_HOST="localhost"
        go build ./...

    - name: Run orchestrator
      run: |
        go run ./cmd/main.go
        cd orchestrator
    
    - name: Run integration tests
      run: |
        cd integration_tests
        go test -race ./...