name: Integration_Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Build Orchestrator
        run: |
          cd orchestrator
          go build -o ../orchestrator cmd/main.go

      - name: Run Orchestrator in background
        run: |
          nohup ./orchestrator > orchestrator.log 2>&1 &
          sleep 15

      - name: Wait for server to start
        run: |
          for i in {1..15}; do
            echo "Waiting for port 5000... Attempt $i"
            nc -zv localhost 5000 && break || sleep 2
          done

      - name: Show orchestrator logs
        if: always()
        run: cat orchestrator.log

      - name: Run integration tests
        run: |
          cd integration_tests
          go test -race ./...